name: app_utils
description: "TODO: add description"
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter:
#   uses-material-design: true
