name: fridge_manager
description: "An app to manage product expiration dates."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  local_storage_products_api:
    path: packages/local_storage_products_api
  products_api:
    path: packages/products_api
  products_repository:
    path: packages/products_repository
  app_ui:
    path: packages/app_ui
  app_utils:
    path: packages/app_utils
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.27.7
  flutter_timezone: ^1.0.8

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  output_dir: lib/l10n
