name: fridge_manager
description: "An app to manage product expiration dates."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  # core
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  uuid: ^4.4.0

  # localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # bloc
  bloc: ^8.1.4
  meta: ^1.12.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0

  # firebase
  firebase_core: ^3.1.1

  firebase_auth: ^5.1.2
  firebase_ui_auth: ^1.15.0

  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3

  cloud_firestore: ^5.0.2

  # notifications
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8

  # products
  openfoodfacts: ^3.12.0
  mobile_scanner: ^5.1.1

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ui
  flutter_expandable_fab: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7
  test: ^1.25.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  output_dir: lib/l10n

flutter_launcher_icons:
  image_path: "assets/icon/icon_combined.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  adaptive_icon_monochrome: "assets/icon/icon_foreground.png"
  adaptive_icon_background: "#102E3B"
