name: products_api
description: The interface and models for an API providing access to products.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

# TODO: adjust dependency constraints
dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.9.0
  meta: ^1.7.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  # test: ^1.21.4