name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter:
#   uses-material-design: true
